### PR TITLE
Amin branch following module

### PR DESCRIPTION
**Pull request by cleopatez**
DONE:
- Allow users to follow any organizer.
- Set condition if user has already been followed.
- Set Text for Name and Joined Date for User and Organizer Profile.

TODO:
- Working on Rating module.
- Add pictures to User and Organizer Profile (based on Fariz's  work).

### CODE REVIEW

**Comment by Triologee** [comment]
for images, ill do my best to retrieve image from BLOB, if it doesnt work we might need to change to a proper file storage in order to retrieve it, so kiv on that okay

**Comment by cleopatez** [comment]
Aku tgk sebijik kat figma  cam takda pula tunjuk button lepas followed sksks. For now, I tukar the text button if the user has been followed. @sbrnmrzk

**Comment by cleopatez** [comment]
Ce check balik @sbrnmrzk  @Triologee

**Comment by cleopatez** [comment]
InsyaAllah done for following module. Plz check mastah @Triologee  @sbrnmrzk

**Review by Triologee — APPROVED** [review]
with full trust i gib acceptance!

**Pull request merged**
